# Variables to be set: PROJECT_DIR

# SITE AND INSTRUMENT
instrument_number: SN115
site_name: mc
site_abbrev: mc
start_date:
end_date:
coords:
  lat: 48.148
  lon: 16.438
  alt: 0.18
coord_file:
utc_offset: 0.0

# BEHAVIOUR
min_interferogram_size: 0.0
start_with_spectra: False
delete_abscosbin_files: True
delete_input_files: False
note:
proffast_path: %PROJECT_DIR%/src/pylot/prf

# TCCON
tccon_mode: False
tccon_setting:  0

# INPUT PATHS
interferogram_path: %PROJECT_DIR%/example/mc_ifg
map_path: %PROJECT_DIR%/example/mc_map
pressure_path: %PROJECT_DIR%/example/mc_pressure
pressure_type_file: %PROJECT_DIR%/src/pylot_datalogger_format.yml

# OUTPUT PATHS
analysis_path: %PROJECT_DIR%/example/outputs/analysis
result_path: %PROJECT_DIR%/example/outputs
