[tool.poetry]
name = "extract-retrieval-data"
version = "0.1.0"
description = ""
authors = ["Marlon Mueller <marlon.mueller@tum.de>","Moritz Makowski <moritz.makowski@tum.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
attrs = "^22.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 95

[tool.mypy]
strict = true
implicit_reexport = true