[tool.poetry]
name = "extract-retrieval-data"
version = "0.1.0"
description = ""
authors = ["Vyas Giridharan <vyas.giridharan@tum.de>","Moritz Makowski <moritz.makowski@tum.de>"]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
