name: "Continuous Integration"

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10"]
    
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Install poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.in-project true
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install missed dependencies
        run: poetry install

      - name: Format with black
        run: poetry run black . --check --diff

      - name: Type check with mypy
        run: poetry run mypy . --strict --implicit-reexport
      
      #- name: Test with pytest
      #  run: poetry run pytest --cov=.