name: "test"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"
      - name: Install dependencies
        run: pip install ".[dev]"

      - name: Load cached sample data and proffast code
        uses: actions/cache@v4
        with:
          path: |
            data/testing/container/em27-retrieval-pipeline-test-inputs-1.0.0.tar.gz
            src/retrieval/algorithms/proffast-1.0/main/prf
            src/retrieval/algorithms/proffast-2.2/main/prf
            src/retrieval/algorithms/proffast-2.3/main/prf
            src/retrieval/algorithms/proffast-2.4/main/prf
          key: v1.0.0-ci-cache

      # Run quick tests for all python versions except 3.10
      - name: Run quick tests
        if: ${{ matrix.python_version != '3.10' }}
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pytest -m "quick" --cov=src tests/

      # Run all tests for python 3.10
      - name: Run quick and ci tests
        if: ${{ matrix.python_version == '3.10' }}
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pytest -m "quick or ci" --capture=no --cov=src tests/
