name: "test"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.11", "3.12", "3.13", "3.14"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Pull Git LFS files
        run: |
          git lfs install
          git lfs pull
          git lfs ls-files

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran unzip

      - name: Install dependencies
        run: pip install ".[dev]"
      
      # - name: Load cached proffast code
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       src/retrieval/algorithms/proffast-1.0/main/prf
      #       src/retrieval/algorithms/proffast-2.2/main/prf
      #       src/retrieval/algorithms/proffast-2.3/main/prf
      #       src/retrieval/algorithms/proffast-2.4/main/prf
      #     key: v1.11.0-ci-cache

      - name: Run ruff formatter and linter
        run: ruff format --check . && ruff check .

      - name: Run quick and ci tests
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pytest -m "quick or ci" --capture=no tests/

      - name: Upload retrieval logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: retrieval-ci-debug-logs
          path: |
            data/logs/retrieval/
            data/testing/outputs/individual-results/
            data/containers/
          if-no-files-found: ignore